### ISSUE TITLE
Apply Dynamic Category Rules via CLI

### ISSUE THREAD

**Issue by MagefanCustomer** [magefan/magento-2-dynamic-categories#2]
I want apply the rules for Dynamic Category using the CLI command. But I always get an error: Area code not set.
![image (3)](https://user-images.githubusercontent.com/60265400/190096983-0c45ce8f-b08e-4b0e-a072-960d30980908.png)

**Comment by magefan** [comment]
This issue appears because of indexation. The fix will be available in [Magento 2 Dynamic Category Extension](https://magefan.com/magento-2-dynamic-categories) v2.1.1.
